Controllers/ClaimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Grade56_SSO.Controllers
{
    [Authorize]
    public class ClaimsController : Controller
    {
        // GET: Claims
        /// <summary>
        /// Add user's claims to viewbag
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var userClaims = User.Identity as System.Security.Claims.ClaimsIdentity;

            //You get the user’s first and last name below:
            ViewBag.Name = userClaims?.FindFirst("name")?.Value;

            // The 'preferred_username' claim can be used for showing the username
            ViewBag.Username = userClaims?.FindFirst("preferred_username")?.Value;

            // The subject/ NameIdentifier claim can be used to uniquely identify the user across the web
            ViewBag.Subject = userClaims?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            // TenantId is the unique Tenant Id - which represents an organization in Azure AD
            ViewBag.TenantId = userClaims?.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid")?.Value;
                                                                                                                                                                                                                                                                                                                                       
            return View();
        }

    }
}

Controllers/HomeController.cs
// Created a new controller to expose sign-in and sign-out methods

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;

namespace Grade56_SSO.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }


        /* 
        Added the following methods to handle sign-in and sign-out top your controller
        by initiating and authenticating challenge via code.
        */
        /// <summary>
        /// Send an OpenID Connect sign-in request
        /// </summary>
        public void SignIn()
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(
                new AuthenticationProperties { RedirectUri = "/" },
                OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }

        }

        /// <summary>
        /// Send an OpenID Connect sign-out request
        /// </summary>
        public void SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut(
            OpenIdConnectAuthenticationDefaults.AuthenticationType,
            CookieAuthenticationDefaults.AuthenticationType);
        }
    }
}

Views/Claims/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sign-In with Microsoft Office 365 Single Sign-On</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
</head>
<body style="padding:50px">
    <h3>Main Claims:</h3>
    <table class="table table-striped table-bordered table-hover">
        <tr><td>Name</td><td>@ViewBag.Name</td></tr>
        <tr><td>Username</td><td>@ViewBag.Username</td></tr>
        <tr><td>Subject</td><td>@ViewBag.Subject</td></tr>
        <tr><td>TenantId</td><td>@ViewBag.TenantId</td></tr>
    </table>
    <br />
    <h3>All Claims:</h3>
    <table class="table table-striped table-bordered table-hover table-condensed">
        @foreach (var claim in ((System.Security.Claims.ClaimsIdentity)User.Identity).Claims)
        {
            <tr><td>@claim.Type</td><td>@claim.Value</td></tr>
        }
    </table>
    <br />
    <br />
    @Html.ActionLink("Sign out", "SignOut", "Home", null, new { @class = "btn btn-primary" })
</body>
</html>


Views/Home/Index.cshtml

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sign-In with Microsoft Office 365 Guided Setup</title>
    
</head>
<body>
    
    <main>
        <div class="container-fluid">
            @if (!Request.IsAuthenticated)
            {
                
                <div class="row" style="padding:20% 0;">
                    <div class="col-md-2"></div>
                    <div class="col-md-8" style="text-align:center;">
                        <h1 style="font-size:50px;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">Welcome to Grade56 eClass</h1>
                        @*<p>Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>*@
                        <br /><br /><br />
                        <p>
                            <a href="@Url.Action("SignIn", "Home")" style="text-decoration: none;">
                                <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="300px" height="50px" viewBox="0 0 3278 522" class="SignInButton">
                                <style type="text/css">
                                    .fil0:hover {
                                        fill: #4B4B4B;
                                    }

                                    .fnt0 {
                                        font-size: 260px;
                                        font-family: 'Segoe UI Semibold', 'Segoe UI';
                                        text-decoration: none;
                                    }
</style>
                                <rect class="fil0" x="2" y="2" width="3174" height="517" fill="black" />

                                <rect x="150" y="129" width="122" height="122" fill="#F35325" />

                                <rect x="284" y="129" width="122" height="122" fill="#81BC06" />

                                <rect x="150" y="263" width="122" height="122" fill="#05A6F0" />

                                <rect x="284" y="263" width="122" height="122" fill="#FFBA08" />

                                <text x="470" y="357" fill="white" class="fnt0">Sign in with Microsoft</text>
        </svg>
                            </a>
                        </p>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            }
            else
            {
                <span><br />Hello @((User.Identity as System.Security.Claims.ClaimsIdentity)?.FindFirst("name")?.Value)</span>
                <br /><br />
                @Html.ActionLink("See Your Claims", "Index", "Claims")
                <br /><br />
                @Html.ActionLink("Sign out", "SignOut", "Home")
            }
            @if (!string.IsNullOrWhiteSpace(Request.QueryString["errormessage"]))
            {
                <div style="background-color:red;color:white;font-weight: bold;">Error: @Request.QueryString["errormessage"]</div>
            }
        </div>
    </main>
</body>
</html>


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/images/logo1.png" rel="icon" />
    <title>Grade56 eClass Platform</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body style="background-color:#333; color:white;">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color:#ffb900;">
        @*<a class="navbar-brand" style="color:rgb(56, 55, 55)" href="#">Navbar</a>*@
        <a class="navbar-brand" href="#">
            <img src="~/images/logo.png" width="120" height="50" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" >
                <li class="nav-item active" >
                    <a class="nav-link" style="color:rgb(56, 55, 55)" href="#">Grade56 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color:rgb(56, 55, 55)" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color:rgb(56, 55, 55)" href="#">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color:rgb(56, 55, 55)" href="#" tabindex="-1" aria-disabled="true">Email & Apps</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="text-align:center;padding-top:5%;">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <h5>Support</h5>
                        <ul style="list-style:none;text-align:left;margin-left:25%;line-height:30px;">
                            <a href="#" style="color:white;"><li>Account Profile</li></a>
                            <a href="#" style="color:white;"><li>Support</li></a>
                            <a href="#" style="color:white;"><li>About Us</li></a>
                            <a href="#" style="color:white;"><li>Sitemap</li></a>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h5>Education</h5>
                        <ul style="list-style:none;text-align:left;margin-left:25%;line-height:30px;">
                            <a href="#" style="color:white;"><li>Microsoft in Education</li></a>
                            <a href="#" style="color:white;"><li>Office 365 for schools</li></a>
                            <a href="#" style="color:white;"><li>Office for Students</li></a>
                            <a href="#" style="color:white;"><li>Instructors</li></a>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h5>Enterprise</h5>
                        <ul style="list-style:none;text-align:left;margin-left:25%;line-height:30px;">
                            <a href="#" style="color:white;"><li>Concepts</li></a>
                            <a href="#" style="color:white;"><li>Enterprise</li></a>
                            <a href="#" style="color:white;"><li>Microsoft partner resources</li></a>
                            <a href="#" style="color:white;"><li>Affiliates</li></a>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h5>Social Hub</h5>
                        <br />
                        <a href="#"><i class="fa fa-facebook rounded-circle" style="padding:3.5% 0;color:white;background-color:#4267b2;font-size:15px;height:30px;width:30px;"></i></a>
                        <a href="#"><i class="fa fa-twitter rounded-circle" style="padding:3.5% 0;color:white;background-color:#38A1F3;font-size:15px;height:30px;width:30px;"></i></a>
                        <a href="#"><i class="fa fa-instagram rounded-circle" style="padding:2.8% 1.5%;color:white;background-color:rgb(242, 44, 189);font-size:15px;height:30px;width:30px;"></i></a>
                        <a href="#"><i class="fa fa-linkedin rounded-circle" style="padding:3% 0;color:white;background-color:#0077B5;font-size:15px;height:32px;width:32px;"></i></a>
                        <a href="#"><i class="fa fa-google-plus rounded-circle" style="padding:3% 0;color:white;background-color:red;font-size:15px;height:30px;width:30px;"></i></a>
                    </div>
                </div>
            </div>
            <hr />
            <p>&copy; @DateTime.Now.Year Sidmach Technologies Nigeria Limited. All rights reserved.</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>